package com.zte.web.myproject5.model;

public class Product {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column newProduct.A_T
     *
     * @mbg.generated
     */
    private Integer aT;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column newProduct.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column newProduct.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column newProduct.price
     *
     * @mbg.generated
     */
    private Integer price;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column newProduct.A_T
     *
     * @return the value of newProduct.A_T
     *
     * @mbg.generated
     */
    public Integer getaT() {
        return aT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column newProduct.A_T
     *
     * @param aT the value for newProduct.A_T
     *
     * @mbg.generated
     */
    public void setaT(Integer aT) {
        this.aT = aT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column newProduct.id
     *
     * @return the value of newProduct.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column newProduct.id
     *
     * @param id the value for newProduct.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column newProduct.name
     *
     * @return the value of newProduct.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column newProduct.name
     *
     * @param name the value for newProduct.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column newProduct.price
     *
     * @return the value of newProduct.price
     *
     * @mbg.generated
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column newProduct.price
     *
     * @param price the value for newProduct.price
     *
     * @mbg.generated
     */
    public void setPrice(Integer price) {
        this.price = price;
    }
}